=== LibreDemat/libredemat/GUIWizard/conf/processes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:annotation>
  <xs:documentation xml:lang="en">
   Process description schema		
  </xs:documentation>
 </xs:annotation>
 
  <xs:element name="cvqprocess">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="globals" type="GlobalsDefinitionType" minOccurs="0" maxOccurs="1" />
	    <xs:element name="processes" type="ProcessDefinitionType" minOccurs="0" maxOccurs="1" />
	  </xs:sequence>
	</xs:complexType>
  </xs:element>
  
 <xs:complexType name="GlobalsDefinitionType">
  <xs:sequence>
   <xs:element name="session" type="SessionType"  minOccurs="0" maxOccurs="1" />
   <xs:element name="timeout" type="TimeoutType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="help" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="style" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="script" type="ScriptType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="initscript" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="stagedef" type="StageDefType" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name="ProcessDefinitionType">
  <xs:sequence>
   <xs:element name="process" type="ProcessType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="group" type="xs:string" default=""/>
  <xs:attribute name="caption" type="xs:string" default=""/>
  <xs:attribute name="order" type="xs:int"/>
 </xs:complexType>

 <xs:complexType name="TimeoutType">
  <xs:attribute name="cookie" type="xs:string" />
  <xs:attribute name="delay" type="xs:integer" />
  <xs:attribute name="href" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ScriptType">
  <xs:attribute name="src" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="SessionType">
  <xs:attribute name="data" type="xs:string" />
  <xs:attribute name="type" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ProcessType">
  <xs:sequence>
   <xs:element name="title" type="xs:string" />
   <xs:element name="confirm" type="ConfirmType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="script" type="ScriptType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="package" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="persistence" type="xs:string" minOccurs="1" maxOccurs="1" />
   <xs:element name="information" type="InformationType" minOccurs="0" maxOccurs="1" />
   <xs:element name="welcome" type="StateType" minOccurs="0" maxOccurs="1" />
   <xs:element name="stage" type="StageType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="override" type="OverrideType" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="caption" type="xs:string" />
  <xs:attribute name="extends" type="xs:string" />
  <xs:attribute name="subject" type="xs:boolean" default="false"/>
  <xs:attribute name="time" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="InformationType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="label" type="xs:string" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="OverrideType">
  <xs:sequence>
   <xs:element name="stage" type="StageType" minOccurs="0" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="stage" type="xs:string" />
 </xs:complexType>
 
  <xs:complexType name="StageDefType">
    <xs:complexContent>
      <xs:extension base="StageType">
        <xs:sequence>
          <xs:element name="package" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

 <xs:complexType name="StageType">
  <xs:sequence>
   <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="notice" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="info" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="condition" type="ConditionType" minOccurs="0" maxOccurs="1" />
   <xs:element name="confirm" type="ConfirmType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="default" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="previous" type="ButtonType" minOccurs="0" maxOccurs="1" />
   <xs:element name="next" type="ButtonType" minOccurs="0" maxOccurs="1" />
   <xs:element name="script" type="ScriptType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="state" type="StateType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="select" type="SelectType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="menu" type="MenuType" minOccurs="0" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="caption" type="xs:string" />
  <xs:attribute name="ref" type="xs:string"/>
  <xs:attribute name="stagemenu" type="xs:string"/>
  <xs:attribute name="required" type="xs:boolean" default="true"/>
 </xs:complexType>
 
 <xs:complexType name="StateType">
  <xs:sequence>
   <xs:element name="title" type="TitleType" minOccurs="0" maxOccurs="1" />
   <xs:element name="subtitle" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="condition" type="ConditionType" minOccurs="0" maxOccurs="1" />
   <xs:element name="form" type="ContentType" minOccurs="1" maxOccurs="unbounded" />
   <xs:element name="button" type="ButtonType" minOccurs="0" maxOccurs="6" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="change" type="xs:string" />
  <xs:attribute name="context" type="xs:string" />
  <xs:attribute name="buttonArea" type="xs:string" default=""/>
  <xs:attribute name="mode" type="xs:string" default=""/>
 </xs:complexType>
 
 <xs:complexType name="TitleType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="type" type="xs:string" default=""/>
	<xs:attribute name="force" type="xs:boolean" default="false"/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="ContentType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="condition" type="xs:string" default=""/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="SelectType">
  <xs:sequence>
   <xs:element name="title"	type="xs:string" />
   <xs:element name="display" type="DisplayType" maxOccurs="unbounded" />
   <xs:element name="action" type="ActionType" />
   <xs:element name="button" type="ButtonType" minOccurs="0" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="property" type="xs:string" />
  <xs:attribute name="state" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="MenuType">
  <xs:sequence>
   <xs:element name="title"	type="xs:string" />
   <xs:element name="button" type="ButtonType" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="state" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ConditionType">
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="property" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ConfirmType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="script" type="xs:string" />
	<xs:attribute name="check" type="xs:string" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="DisplayType">
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="initial" type="xs:boolean" default="false"/>
  <xs:attribute name="type" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ActionType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
    <xs:attribute name="confirm" type="xs:string" default="" />
    <xs:attribute name="transition" type="xs:string" default="" />
	<xs:attribute name="parameter" type="xs:string" default="" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="ButtonType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="confirm" type="xs:string" />
	<xs:attribute name="script" type="xs:string" />
	<xs:attribute name="action" type="xs:string" />
	<xs:attribute name="default" default="false" type="xs:boolean" />
	<xs:attribute name="transition" default="" type="xs:string" />
	<xs:attribute name="type" type="xs:string" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
</xs:schema>

=== LibreDemat/libredemat/FrontOffice/webapp/WEB-INF/guiwizard/citizen.xml
<?xml version="1.0" encoding="UTF-8" ?>

<cvqprocess xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:noNamespaceSchemaLocation="processes.xsd" >

<!--****************** PROCESSUS DEMANDE CARTE VALOISE *****************-->
  <processes group="citizen">
	<process name="eFamily" caption="Modifier mon compte" extends="eCitizen" time="5" >
		<title>Modification de mon compte</title>
		<confirm name="familyHome" check="noModificationRequest">Compte pas encore validé, ou une demande de modification est déja en cours.</confirm>
        <persistence>fr.cg95.cvq.fo.citizen.AccountPersistence</persistence>
		<override stage="Justificatifs" />
	</process>
	
	<process name="eCitizen" time="10" >
		<title>Création de compte</title>
		<script src="./js/citizen/citizen.js" />
		<package>fr.cg95.cvq.fo.citizen</package>
        <persistence>fr.cg95.cvq.fo.citizen.AccountPersistence</persistence>
		
		<!-- *******************INSCRIPTION ADULTE *********************-->
		<stage name="Adult" caption="Adultes" stagemenu="add">
			<title>Les adultes de votre compte</title>
			<info>Renseigner les adultes du foyer</info>

			<confirm name="cancel">Attention ! Les données de la personne n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
			<confirm name="delete">Voulez-vous vraiment supprimer la personne sélectionnée ?</confirm>
			<confirm name="delete">Voulez-vous vraiment supprimer l'adulte sélectionné ?\nAttention: toutes les informations rélatives à l'adulte seront supprimés!</confirm>
			<confirm name="changed" check="state">Vos modifications éventuelles seront perdu ! Voulez-vous continuer ?</confirm>
			<confirm name="terminate">Voulez-vous vraiment annuler votre demande ?</confirm>

			<default>adult</default>
				
			<previous confirm="terminate">endProcess</previous>

			<state name="display" mode="static">
				<title>Consulter un adulte</title>
				<form>/citizen/adult/display</form>
				<button confirm="delete" action="del">Supprimer</button>
				<button transition="adult" action="">Modifier</button>
			</state>
			
			<state name="adult" change="confirm">
				<title>Ajouter un adulte</title>
				<form>/citizen/adult/adult</form>
				<button confirm="cancel" action="cancel" transition="adult">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="" transition="address">Page suivante</button>
			</state>
											
			<state name="address">
				<title>Ajouter un adulte</title>
				<form>/citizen/adult/address</form>
				<button script="processSubmit" action="" transition="adult">Page précédente</button>
				<button confirm="cancel" action="cancel" transition="address">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="save" transition="display">Enregistrer</button>
			</state>
											
			<select name="fr.cg95.cvq.fo.common.Request" property="list(adult)" state="all">
				<title>Les adultes</title>
				<display type="people"/>
				<display name="adultFirstName"/>
				<display name="adultLastName" initial="true"/>
				<action confirm="changed" parameter="index" transition="display">get</action> 
				<button action="new" transition="adult">Ajouter un adulte</button>
			</select>
		</stage>
		
		<!--********************* INSCRIPTION ENFANT ************************-->
		<stage name="Child" caption="Enfants" stagemenu="add" required="false" >
			<title>Les enfants de votre compte</title>
			<info>Renseigner les enfants du foyer</info>

			<confirm name="cancel">Attention ! Les données de la personne n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
			<confirm name="delete">Voulez-vous vraiment supprimer l'enfant sélectionné ?\nAttention: toutes les informations rélatives à l'enfant seront supprimés!</confirm>
			<confirm name="changed" check="state">Vos modifications éventuelles seront perdu ! Voulez-vous continuer ?</confirm>
			<confirm name="terminate">Voulez-vous vraiment annuler votre demande ?</confirm>

			<default>default</default>
				
			<state name="default">
				<title>Ajouter un enfant</title>
				<form>/citizen/child/default</form>
			</state>
			
			<state name="display" mode="static">
				<title>Consulter un enfant</title>
				<form>/citizen/child/display</form>
				<form>/citizen/child/displaylegal</form>
				<button confirm="delete" action="del" transition="default">Supprimer</button>
				<button transition="child" action="">Modifier</button>
			</state>
			
			<state name="child" change="confirm">
				<title>Ajouter un enfant</title>
				<form>/citizen/child/child</form>
				<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="" transition="legal">Page suivante</button>
			</state>
											
			<state name="legal" change="confirm" mode="static">
				<title>Ajouter un enfant</title>
				<form>/citizen/child/adults</form>
				<form>/citizen/child/legal</form>
				<form>/citizen/child/explain</form>
				<button type="add" script="processSubmit" action="new&amp;list=childLegalResponsible" transition="legaladult">Ajouter responsable</button>
				<button script="processSubmit" action="" transition="child">Page précédente</button>
				<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
				<button default="true" confirm="legal" script="processChildSubmit" action="save" transition="display">Enregistrer</button>
			</state>
											
			<state name="legaladult" change="confirm" context="Responsible">
				<title>Ajouter un responsable légal</title>
				<form>/citizen/responsible/adult</form>
				<button confirm="cancel" action="" transition="">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="" transition="legaladdress">Page suivante</button>
			</state>
											
			<state name="legaladdress" context="Responsible">
				<title>Ajouter un responsable légal</title>
				<form>/citizen/responsible/address</form>
				<button script="processSubmit" action="" transition="legaladult">Page précédente</button>
				<button confirm="cancel" action="" transition="">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="save&amp;list=childLegalResponsible" transition="legaldisplay">Enregistrer</button>
			</state>
			
			<state name="legaldisplay" context="Responsible" mode="static">
				<title>Ajouter un responsable légal</title>
				<form>/citizen/responsible/display</form>
				<button confirm="delete" action="del&amp;list=childLegalResponsible" transition="">Supprimer</button>
				<button transition="legaladult" action="">Modifier</button>
				<button type="next" default="true" action="" transition="">Page suivante</button>
			</state>
			
			<select name="fr.cg95.cvq.fo.common.Request" property="list(child)" state="all">
				<title>Les enfants</title>
				<display type="people"/>
				<display name="childFirstName"/>
				<display name="childLastName" initial="true"/>
				<action confirm="changed" parameter="index" transition="display">get</action> 
				<button action="new" transition="child">Ajouter un enfant</button>
			</select>
		</stage>
		
		<!--********************** AJOUT JUSTIFICATIFS ***********************-->
		<stage ref="Documents" caption="Justificatifs"/>
		
		<!--************************ DEFINITION COMPTE **********************-->
		<stage name="Account" caption="Définition Compte" stagemenu="display">
			<title>Identifiant pour accéder à votre espace personnel</title>
			<info>Enregistrer les éléments pour la création de votre compte</info>
			<default>account</default>
			
			<state name="account" context="Account">
				<title>Processus d'inscription</title>
				<form>/citizen/account/account</form>
				<button default="true" script="processAccountSubmit" action="next">Enregistrer</button>
			</state>

			<state name="exists" context="Account" mode="static">
				<title>Processus d'inscription</title>
				<form>/citizen/account/exists</form>
			</state>
		</stage>
		
		<!-- ******************* VALIDATION *********************-->
		<stage name="Validation" caption="Validation" stagemenu="display">
			<title>Validation et fin</title>
			<info>Résumé des informations fournies. A valider pour la création de votre espace personnel</info>

			<default>summary</default>

			<next>false</next>
			
			<state name="summary" mode="static">
				<form>/citizen/validation/summary</form>
				<form>/common/validation/documents</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="next" default="true" script="processSubmit" action="" transition="validation">Page suivante</button>
			</state>

			<state name="validation">
				<form>/common/validation/validation</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="save" script="validateRequest()">Enregistrer</button>
			</state>

			<state name="print" buttonArea="none" mode="noreturn">
				<form>/common/validation/print</form>
			</state>

		</stage>
	</process>
  </processes>		
</cvqprocess>

=== LibreDemat/libredemat/FrontOffice/webapp/WEB-INF/guiwizard/localpolice.xml
<?xml version="1.0" encoding="UTF-8"?>
<cvqprocess xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="processes.xsd">
	<processes group="localpolice" caption="Sécurité" order="7">
 	
		<process name="eHolidaySecurity" caption="S&#233;curit&#233; vacances" time="5">
			<title>S&#233;curit&#233; vacances</title>
			<confirm name="familyHome" check="hasAuthorizedSubjects">Vous n'avez aucune personne à inscrire.</confirm>
			<package>fr.cg95.cvq.fo.localpolice</package>
			<persistence>fr.cg95.cvq.fo.localpolice.HolidaySecurityPersistence</persistence>
			<information label="Règlement Sécurité vacances.">txt/ReglementSecu.txt</information>

			<!-- Subject -->
	 		<stage name="Subject" caption="Personne à inscrire">
				<title>Personne à inscrire</title>
				<info>Selection de la personne</info>

				<confirm name="changed" check="state">Vos modifications éventuelles seront perdu ! Voulez-vous continuer ?</confirm>
				<confirm name="cancel">Attention ! les données de la demande n'ont pas été enregistrées</confirm>
				<confirm name="delete">Voules-vous vraiement supprimer les informations sur la demande</confirm>
				<confirm name="terminate">Voulez-vous vraiement abandonner</confirm>
				<confirm name="continue" check="">Vous devez selectionner une personne</confirm>

				<default>default</default>

				<previous confirm="terminate">endProcess</previous>
				<next confirm="continue" />

				<state name="default">
					<title>Le demandeur</title>
					<form>/localpolice/subject/default</form>
				</state>
				<state name="subject">
					<title>Le demandeur</title>
					<form>/localpolice/subject/subject</form>
					<button confirm="cancel" action="resetProcess" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="" transition="display">Enregistrer</button>
				</state>
				<state name="display" mode="static">
					<title>Le demandeur</title>
					<form>/localpolice/subject/display</form>
					<button confirm="delete" action="resetProcess" transition="default">Supprimer</button>
					<button action="" transition="subject">Modifier</button>
				</state>
				<select name="familyHome" property="selectionListWithoutCurrent" state="default" >
					<title>Adulte(s) du compte</title>
					<display type="people"/>
					<display name="firstName"/>
					<display name="lastName"  initial="true"/>
					<action confirm="changed" parameter="index" transition="subject">createRequest</action>
				</select>
				<select name="familyHome" property="individualToRegister" state="all">
					<title>Adulte à inscrire</title>
					<display type="people"/>
					<display name="firstName"/>
					<display name="lastName"  initial="true"/>
					<action parameter="index" transition="display">processStage</action>
				</select>
			</stage>

			<!-- document -->
		 	<stage ref="Documents"/>

			<!-- Date -->

			<stage name="Absencedate" caption="Dates de l'absence" stagemenu="display">
				<title>Date de l'absence</title>
				<info>Date de début et de fin de l'absence</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Date de début et de fin d'absence</title>
					<form>/localpolice/absencedate/absencedate</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- réglement -->

			<stage name="Rules" caption="Réglement" stagemenu="display">
				<title>Réglement du service</title>
				<info>Réglement du service à souscrire</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Souscription au réglement</title>
					<form>/common/rules/rules</form>
					<form>/localpolice/rules/authorisation</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- telephone d'alerte -->

			<stage name="Alertphone" caption="Téléphone de contact" stagemenu="display">
				<title>Téléphone de contact d'alerte</title>
				<info>Téléphone de liaison en cas d'alerte </info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Téléphone d'alerte</title>
					<form>/localpolice/alertphone/alertphone</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- Personne à contacter -->

			<stage name="Othercontact" caption="Autre contact" stagemenu="display" required="false">
				<title>Personne à contacter</title>
				<info>Personne à contacter en cas d'alerte</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Personne à contacter</title>
					<form>/localpolice/othercontact/othercontact</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- Info complémentaire -->

			<stage name="Securityfacility" caption="Information complémentaire" stagemenu="display" required="false">
				<title>Info complémentaire</title>
				<info>Information sur la présence d'une alarme ou d'un éclairage automatique</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default">
					<title>Info complémentaire</title>
					<form>/localpolice/securityfacility/securityfacility</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- Validation -->

			<stage name="Validation" caption="Validation" stagemenu="display">
				<title>Validation</title>
				<info>Résumé des informations fournies. A valider pour la création de votre demande</info>

				<default>summary</default>

				<next>false</next>

				<state name="summary" mode="static">
					<form>/common/validation/requester</form>
					<form>/localpolice/validation/summary</form>
					<button type="quit" script="cancelRequest()">Annuler la demande</button>
					<button type="next" default="true" script="processSubmit" action="" transition="validation">Page suivante</button>
				</state>
				<state name="validation">
					<form>/common/validation/validation</form>
					<button type="quit" script="cancelRequest()">Annuler la demande</button>
					<button type="save" script="validateRequest()">Enregistrer</button>
				</state>

				<state name="trace">
					<form>/common/validation/trace</form>
					<button type="quit" script="cancelRequest()">Annuler la demande</button>
					<button type="save" script="validateRequest()">Enregistrer</button>
				</state>

				<state name="print" buttonArea="none" mode="noreturn">
					<form>/common/validation/print</form>
				</state>
			</stage>
		</process>

	</processes>
</cvqprocess>
