=== LibreDemat/libredemat/GUIWizard/conf/processes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:annotation>
  <xs:documentation xml:lang="en">
   Process description schema		
  </xs:documentation>
 </xs:annotation>
 
  <xs:element name="cvqprocess">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="globals" type="GlobalsDefinitionType" minOccurs="0" maxOccurs="1" />
	    <xs:element name="processes" type="ProcessDefinitionType" minOccurs="0" maxOccurs="1" />
	  </xs:sequence>
	</xs:complexType>
  </xs:element>
  
 <xs:complexType name="GlobalsDefinitionType">
  <xs:sequence>
   <xs:element name="session" type="SessionType"  minOccurs="0" maxOccurs="1" />
   <xs:element name="timeout" type="TimeoutType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="help" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="style" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="script" type="ScriptType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="initscript" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="stagedef" type="StageDefType" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
 </xs:complexType>

 <xs:complexType name="ProcessDefinitionType">
  <xs:sequence>
   <xs:element name="process" type="ProcessType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="group" type="xs:string" default=""/>
  <xs:attribute name="caption" type="xs:string" default=""/>
  <xs:attribute name="order" type="xs:int"/>
 </xs:complexType>

 <xs:complexType name="TimeoutType">
  <xs:attribute name="cookie" type="xs:string" />
  <xs:attribute name="delay" type="xs:integer" />
  <xs:attribute name="href" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ScriptType">
  <xs:attribute name="src" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="SessionType">
  <xs:attribute name="data" type="xs:string" />
  <xs:attribute name="type" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ProcessType">
  <xs:sequence>
   <xs:element name="title" type="xs:string" />
   <xs:element name="confirm" type="ConfirmType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="script" type="ScriptType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="package" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="persistence" type="xs:string" minOccurs="1" maxOccurs="1" />
   <xs:element name="information" type="InformationType" minOccurs="0" maxOccurs="1" />
   <xs:element name="welcome" type="StateType" minOccurs="0" maxOccurs="1" />
   <xs:element name="stage" type="StageType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="override" type="OverrideType" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="caption" type="xs:string" />
  <xs:attribute name="extends" type="xs:string" />
  <xs:attribute name="subject" type="xs:boolean" default="false"/>
  <xs:attribute name="time" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="InformationType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="label" type="xs:string" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="OverrideType">
  <xs:sequence>
   <xs:element name="stage" type="StageType" minOccurs="0" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="stage" type="xs:string" />
 </xs:complexType>
 
  <xs:complexType name="StageDefType">
    <xs:complexContent>
      <xs:extension base="StageType">
        <xs:sequence>
          <xs:element name="package" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

 <xs:complexType name="StageType">
  <xs:sequence>
   <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="notice" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="info" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="condition" type="ConditionType" minOccurs="0" maxOccurs="1" />
   <xs:element name="confirm" type="ConfirmType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="default" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="previous" type="ButtonType" minOccurs="0" maxOccurs="1" />
   <xs:element name="next" type="ButtonType" minOccurs="0" maxOccurs="1" />
   <xs:element name="script" type="ScriptType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="state" type="StateType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="select" type="SelectType" minOccurs="0" maxOccurs="unbounded" />
   <xs:element name="menu" type="MenuType" minOccurs="0" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="caption" type="xs:string" />
  <xs:attribute name="ref" type="xs:string"/>
  <xs:attribute name="stagemenu" type="xs:string"/>
  <xs:attribute name="required" type="xs:boolean" default="true"/>
 </xs:complexType>
 
 <xs:complexType name="StateType">
  <xs:sequence>
   <xs:element name="title" type="TitleType" minOccurs="0" maxOccurs="1" />
   <xs:element name="subtitle" type="xs:string" minOccurs="0" maxOccurs="1" />
   <xs:element name="condition" type="ConditionType" minOccurs="0" maxOccurs="1" />
   <xs:element name="form" type="ContentType" minOccurs="1" maxOccurs="unbounded" />
   <xs:element name="button" type="ButtonType" minOccurs="0" maxOccurs="6" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="change" type="xs:string" />
  <xs:attribute name="context" type="xs:string" />
  <xs:attribute name="buttonArea" type="xs:string" default=""/>
  <xs:attribute name="mode" type="xs:string" default=""/>
 </xs:complexType>
 
 <xs:complexType name="TitleType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="type" type="xs:string" default=""/>
	<xs:attribute name="force" type="xs:boolean" default="false"/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="ContentType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="condition" type="xs:string" default=""/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="SelectType">
  <xs:sequence>
   <xs:element name="title"	type="xs:string" />
   <xs:element name="display" type="DisplayType" maxOccurs="unbounded" />
   <xs:element name="action" type="ActionType" />
   <xs:element name="button" type="ButtonType" minOccurs="0" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="property" type="xs:string" />
  <xs:attribute name="state" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="MenuType">
  <xs:sequence>
   <xs:element name="title"	type="xs:string" />
   <xs:element name="button" type="ButtonType" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="state" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ConditionType">
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="property" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ConfirmType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="script" type="xs:string" />
	<xs:attribute name="check" type="xs:string" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="DisplayType">
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="initial" type="xs:boolean" default="false"/>
  <xs:attribute name="type" type="xs:string" />
 </xs:complexType>
 
 <xs:complexType name="ActionType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
    <xs:attribute name="confirm" type="xs:string" default="" />
    <xs:attribute name="transition" type="xs:string" default="" />
	<xs:attribute name="parameter" type="xs:string" default="" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
 <xs:complexType name="ButtonType">
  <xs:simpleContent>
   <xs:extension base="xs:string">
	<xs:attribute name="confirm" type="xs:string" />
	<xs:attribute name="script" type="xs:string" />
	<xs:attribute name="action" type="xs:string" />
	<xs:attribute name="default" default="false" type="xs:boolean" />
	<xs:attribute name="transition" default="" type="xs:string" />
	<xs:attribute name="type" type="xs:string" />
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 
</xs:schema>

=== LibreDemat/libredemat/FrontOffice/webapp/WEB-INF/guiwizard/urban.xml
<?xml version="1.0" encoding="UTF-8" ?>

<cvqprocess xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	 xsi:noNamespaceSchemaLocation="processes.xsd" >

  <processes group="urban" caption="Urbanisme" order="2">
	<!--****************** PROCESSUS DEMANDES D'ALIGNEMENT *******************-->
	<process name="eAlign" caption="Alignement" time="3">
		<title>Certificat d'alignement</title>
		<package>fr.cg95.cvq.fo.urban.align</package>
        <persistence>fr.cg95.cvq.fo.urban.AlignmentCertificatePersistence</persistence>

	    <!-- ******************* DEMANDEUR *********************-->
		<stage ref="Requester" />
		
		<stage name="Cadastre" caption="Cadastre" stagemenu="display">
			<title>Situation cadastrale de l'immeuble</title>
			<info>Informations cadastrales.</info>

			<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
			<confirm name="delete">Voulez-vous vraiment supprimer les informations sur la qualité du demandeur?</confirm>
			<confirm name="continue" check="">Vous devez enregistrer la page avant de passer à l'étape suivante</confirm>
			<confirm name="terminate">Voulez-vous vraiment abandonner ?</confirm>

			<default>cadastre</default>
			<next confirm="continue"/>
			
			<state name="cadastre">
				<title>Situation cadastrale</title>
				<form>/urban/align/cadastre/cadastre</form>
				<button confirm="cancel" action="" transition="cadastre">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="" transition="display">Enregistrer</button>
			</state>

			<state name="display" mode="static">
				<title>Situation cadastrale</title>
				<form>/urban/align/cadastre/display</form>
				<form condition="requesterQuality==Tenant">/urban/align/cadastre/displayowner</form>
				<button confirm="delete" action="reset" transition="cadastre">Supprimer</button>
				<button transition="cadastre" action="">Modifier</button>
			</state>

		</stage>
		
		<stage ref="Documents"/>
		
		<!-- ******************* VALIDATION *********************-->	
		<stage name="Validation" caption="Validation" stagemenu="display">
			<title>Validation et fin</title>
			<info>Résumé des informations fournies. A valider pour la création de votre demande</info>
		  
			<default>summary</default>

			<next>false</next>
			
			<state name="summary" mode="static">
				<form>/common/validation/requester</form>
				<form>/urban/align/validation/summary</form>
				<form condition="requesterQuality==Tenant">/urban/align/validation/summaryowner</form>
				<form>/common/validation/documents</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="next" default="true" script="processSubmit" action="" transition="validation">Page suivante</button>
			</state>

			<state name="validation">
				<form>/common/validation/validation</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="save" script="validateRequest()">Enregistrer</button>
			</state>

			<state name="trace">
				<form>/common/validation/trace</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="save" script="validateRequest()">Enregistrer</button>
			</state>

			<state name="print" buttonArea="none" mode="noreturn">
				<form>/common/validation/print</form>
			</state>

		</stage>
	</process>

	<process name="eSewer" caption="Raccordement" time="3">
		<title>Raccordement à l'égout</title>
		<package>fr.cg95.cvq.fo.urban.sewer</package>
        <persistence>fr.cg95.cvq.fo.urban.SewerConnectionPersistence</persistence>

	    <!-- ******************* DEMANDEUR *********************-->
		<stage ref="Requester" />
		
		<stage name="Cadastre" caption="Cadastre" stagemenu="display">
			<title>Situation cadastrale de l'immeuble</title>
			<info>Informations cadastrales.</info>

			<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
			<confirm name="delete">Voulez-vous vraiment supprimer les informations sur la qualité du demandeur?</confirm>
			<confirm name="continue" check="">Vous devez enregistrer la page avant de passer à l'étape suivante</confirm>
			<confirm name="terminate">Voulez-vous vraiment abandonner ?</confirm>

			<default>cadastre</default>
			<next confirm="continue"/>
			
			<state name="cadastre">
				<title>Situation cadastrale</title>
				<form>/urban/sewer/cadastre/cadastre</form>
				<button confirm="cancel" action="" transition="cadastre">Annuler Saisie</button>
				<button default="true" script="processSubmit" action="" transition="display">Enregistrer</button>
			</state>

			<state name="display" mode="static">
				<title>Situation cadastrale</title>
				<form>/urban/sewer/cadastre/display</form>
				<form condition="requesterQuality==Tenant">/urban/sewer/cadastre/displayowner</form>
				<button confirm="delete" action="reset" transition="cadastre">Supprimer</button>
				<button transition="cadastre" action="">Modifier</button>
			</state>

		</stage>
		
		<stage ref="Documents"/>
		
		<!-- ******************* VALIDATION *********************-->	
		<stage name="Validation" caption="Validation" stagemenu="display">
			<title>Validation et fin</title>
			<info>Résumé des informations fournies. A valider pour la création de votre demande</info>
		  
			<default>summary</default>

			<next>false</next>
			
			<state name="summary" mode="static">
				<form>/common/validation/requester</form>
				<form>/urban/sewer/validation/summary</form>
				<form condition="requesterQuality==Tenant">/urban/sewer/validation/summaryowner</form>
				<form>/common/validation/documents</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="next" default="true" script="processSubmit" action="" transition="validation">Page suivante</button>
			</state>

			<state name="validation">
				<form>/common/validation/validation</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="save" script="validateRequest()">Enregistrer</button>
			</state>

			<state name="trace">
				<form>/common/validation/trace</form>
				<button type="quit" script="cancelRequest()">Annuler la demande</button>
				<button type="save" script="validateRequest()">Enregistrer</button>
			</state>

			<state name="print" buttonArea="none" mode="noreturn">
				<form>/common/validation/print</form>
			</state>

		</stage>
	</process>
  </processes>		
</cvqprocess>

=== LibreDemat/libredemat/FrontOffice/webapp/WEB-INF/guiwizard/technical.xml
<?xml version="1.0" encoding="UTF-8"?>
<cvqprocess xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="processes.xsd">
	<processes group="technical" caption="Service technique" order="9">

		<process name="eTechnicalIntervention" caption="Intervention technique" time="5">
			<title>Demande d'intervention technique</title>
			<package>fr.cg95.cvq.fo.technical</package>
			<persistence>fr.cg95.cvq.fo.technical.TechnicalInterventionPersistence</persistence>

			<!-- Demandeur -->
			<stage name="Subject" caption="Personne à inscrire">

				<title>Personne à inscrire</title>
				<info>Selection de la personne</info>

				<confirm name="changed" check="state">Vos modifications éventuelles seront perdu ! Voulez-vous continuer ?</confirm>
				<confirm name="cancel">Attention ! les données de la demande n'ont pas été enregistrées</confirm>
				<confirm name="delete">Voules-vous vraiement supprimer les informations sur la demande</confirm>
				<confirm name="terminate">Voulez-vous vraiement abandonner</confirm>
				<confirm name="continue" check="">Vous devez selectionner une personne</confirm>

				<default>default</default>
				<previous confirm="terminate">endProcess</previous>
				<next confirm="continue" />

				<state name="default">
					<title>Le demandeur</title>
					<form>/technical/subject/default</form>
				</state>
				<state name="subject">
					<title>Le demandeur</title>
					<form>/technical/subject/subject</form>
					<button confirm="cancel" action="resetProcess" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="" transition="display">Enregistrer</button>
				</state>
				<state name="display" mode="static">
					<title>Le demandeur</title>
					<form>/technical/subject/display</form>
					<button confirm="delete" action="resetProcess" transition="default">Supprimer</button>
					<button action="" transition="subject">Modifier</button>
				</state>
				<select name="familyHome" property="selectionListWithoutCurrent" state="default" >
					<title>Adulte(s) du compte</title>
					<display type="people"/>
					<display name="firstName"/>
					<display name="lastName"  initial="true"/>
					<action confirm="changed" parameter="index" transition="subject">createRequest</action>
				</select>
				<select name="familyHome" property="individualToRegister" state="all">
					<title>Adulte à inscrire</title>
					<display type="people"/>
					<display name="firstName"/>
					<display name="lastName"  initial="true"/>
					<action parameter="index" transition="display">processStage</action>
				</select>
			</stage>

			<!-- type d'intervention -->
			<stage name="Type" caption="Type d'intervention" stagemenu="display">
				<title>Quel est le type de la demande</title>
				<info>Définition du type de la demande</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Type de demande d'intervention</title>
					<form>/technical/type/type</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>

			</stage>

			<!-- Document -->
			<stage ref="Documents"/>

			<!-- Lieu d'intervention -->
			<stage name="Place" caption="Lieu de l'intervention" stagemenu="display">
				<title>Quel est le lieu de l'intervention</title>
				<info>Définition du lieu de l'intervention</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Lieu d'intervention</title>
					<form>/technical/place/place</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- Description de l'intervention -->
			<stage name="Description" caption="Description de l'intervention" stagemenu="display">
				<title>Description de l'intervention</title>
				<info>Description précise de la demande</info>
				<confirm name="cancel">Attention ! Les données de la demande n'ont pas été enregistrées ! Voulez-vous quand même annuler la saisie ?</confirm>
				<default>default</default>
				<next script="processSubmit" action=""/>

				<state name="default" change="confirm">
					<title>Description de l'intervention</title>
					<form>/technical/description/description</form>
					<button confirm="cancel" action="" transition="default">Annuler Saisie</button>
					<button default="true" script="processSubmit" action="next">Enregistrer</button>
				</state>
			</stage>

			<!-- Validation -->
			<stage name="Validation" caption="Validation" stagemenu="display">
				<title>Validation</title>
				<info>Résumé des informations fournies. A valider pour la création de votre demande</info>

				<default>summary</default>

				<next>false</next>

				<state name="summary" mode="static">
					<form>/common/validation/requester</form>
					<form>/technical/validation/summary</form>
					<button type="quit" script="cancelRequest()">Annuler la demande</button>
					<button type="next" default="true" script="processSubmit" action="" transition="validation">Page suivante</button>
				</state>
				<state name="validation">
					<form>/common/validation/validation</form>
					<button type="quit" script="cancelRequest()">Annuler la demande</button>
					<button type="save" script="validateRequest()">Enregistrer</button>
				</state>
				<state name="trace">
					<form>/common/validation/trace</form>
					<button type="quit" script="cancelRequest()">Annuler la demande</button>
					<button type="save" script="validateRequest()">Enregistrer</button>
				</state>
				<state name="print" buttonArea="none" mode="noreturn">
					<form>/common/validation/print</form>
				</state>
			</stage>
		</process>

	</processes>
</cvqprocess>
